name: "Run multiple Ansible playbooks"
description: "Run Ansible playbooks in phase that represent setup order"

inputs:
  ## Required
  ansible_directory:
    description: Directory where Ansible files are located.
    required: true

  playbook_directory:
    description: | 
      Directory where playbook subfolders are located.
      Assumes that playbooks are located in the dir pointed to by ansible_directory.
    required: true
    default: "/playbooks"

  execution_order:
    description: Order in which to execute the playbooks (comma-separated list of folder names).
    required: true



  ## Optional

#  requirements:
#    description: JSON string mapping playbook names to galaxy requirement
#    required: false

  private_key:
    description: The private key for running Ansible commands.
    required: false

  inventory_file_path:
    description: |
      The path to the inventory file.
      Assumes that the file is located in the dir pointed to by ansible_directory.
    required: false
    default: "/hosts.cfg"

  known_hosts:
    description: Content of the known hosts. If not provided, the host key checking is disabled.
    required: false

  extra_options:
    description: |
      Extra options that are passed to playbook command,
      for example --extra-vars or --inventory
    required: false

  sudo:
    description: Whether to use sudo for executing commands
    required: false
    default: 'false'

outputs:
  results:
    description: Output from each playbook run in JSON format.

runs:
  using: "node16"
  main: "index.js"
  post: "post.js"
