name: "Run multiple Ansible playbooks"
description: "Run Ansible playbooks in phase that represent setup order"

inputs:
  ## Required
  playbook_directory:
    description: "Directory where playbook subfolders are located"
    required: true
    default: "/ansible/playbooks"

  private_key_path:
    description: "The complete path to the private key, for example /home/runner/.ssh/key"
    required: true

  execution_order:
    description: "Order in which to execute the playbooks (comma-separated list of folder names)"
    required: true

  inventory_file_path:
    description: "The complete path to the hosts.cfg file, for example /home/runner/hosts.cfg"
    required: true
    default: "/ansible/hosts.cfg"

  ## Optional

#  requirements:
#    description: JSON string mapping playbook names to galaxy requirement
#    required: false

  extra_options:
    description: Extra options that are passed to playbook command,
      for example --extra-vars or --inventory
    required: false

  sudo:
    description: Whether to use sudo for executing commands
    required: false
    default: 'false'

outputs:
  results:
    description: "output from each playbook run in JSON format"

runs:
  using: "node16"
  main: "index.js"
  #post: "post.js"
