name: "Run multiple Ansible playbooks"
description: "Run Ansible playbooks in phase that represent setup order"

inputs:
  ansible_directory:
    description: Directory where Ansible files are located.
    required: false
    default: "ansible"

  playbook_directory:
    description: | 
      Directory where playbook subfolders are located.
      Assumes that playbooks are located in the dir pointed to by ansible_directory.
    required: true
    default: "playbooks"

  execution_order:
    description: Order in which to execute the playbooks (comma-separated list of folder names).
    required: true

  exclude_dirs:
    description: |
      A comma-separated list of directories which are in the playbook directory
      but should be excluded from execution as they do not represent phases
    required: false

  requirements:
    description: JSON string mapping playbook names to galaxy requirement
    required: false

  private_key:
    description: The private key for running Ansible commands.
    required: false

  inventory_file_path:
    description: |
      The path to the inventory file.
      Assumes that the file is located in the dir pointed to by ansible_directory.
    required: false

  known_hosts:
    description: Content of the known hosts. If not provided, the host key checking is disabled.
    required: false

  extra_options_string:
    description: |
      A multi-line string of extra options to pass to ansible-playbooks.
      Please provide the options in the following way:
      1. each group of options should be separated by double angle brackets (<< >>)
      2. each option in a group should be separated by a new line
      3. extra variables that should be applied to all playbooks should be in the 
       group name <<all>>
    required: false

  extra_options_file:
    description: |
      A path to a file containing extra options to pass to ansible-playbooks.
      The path should be relative to the repository root.

  secrets:
    description: |
      A JSON string mapping secret names to their values.
      The secret names should be the same as the ones used in the playbooks.
    required: false

  sudo:
    description: Whether to use sudo for executing commands
    required: false
    default: 'false'

outputs:
  results:
    description: Output from each playbook run in JSON format.

runs:
  using: "node16"
  main: "index.js"
  post: "post.js"
