- name: Check if zoo and kafka roles work properly
  hosts: zookeeper-nodes

  vars:
    zks: xyz

  roles:
    - role: sleighzy.zookeeper
      zookeeper_servers:
        - "{{ zks }}"

- hosts: kafka-nodes
  roles:
    - role: sleighzy.kafka
      kafka_download_base_url: https://archive.apache.org/dist/kafka

